#cloud-config

coreos:
  etcd:
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
    discovery: https://discovery.etcd.io/<token>
  fleet:
    public-ip: $private_ipv4
  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: docker.socket
      command: start
      drop-ins: 
      - name: 30-ListenStream.conf
        content: |
          [Socket]
          ListenStream=$private_ipv4:2375
    - name: development-machine.service
      content: |
        [Unit]
        Description=machine
        After=docker.service
        Requires=docker.service
        [Service]
        ExecStart=/bin/bash -c 'sudo systemd-nspawn --machine gainmaster --quiet --keep-unit --boot --link-journal=guest --directory /machine --directory /volumes --bind /usr/bin/docker --bind /usr/bin/etcdctl --bind /usr/bin/fleetctl --bind /projects systemctl start sshd'
        ExecStop=/bin/bash -c 'sudo machinectl terminate machine'
        TimeoutStartSec=0
        Restart=always
        RestartSec=10s
        [Install]
        WantedBy=multi-user.target
    - name: skydns.service
      command: start
      content: |
        [Unit]
        Description=SkyDNS service
        Requires=etcd.service
        After=etcd.service
        Requires=docker.service
        After=docker.service
        [Service]
        TimeoutStartSec=0
        KillMode=none
        ExecStartPre=-/usr/bin/docker kill skydns
        ExecStartPre=-/usr/bin/docker rm skydns
        ExecStartPre=/usr/bin/docker pull skynetservices/skydns
        ExecStart=/usr/bin/docker run --rm --name skydns \
          -e "ETCD_MACHINES=http://$private_ipv4:4001" \
          -e "SKYDNS_ADDR=0.0.0.0:53" \
          -e "SKYDNS_DOMAIN=gainmaster.local" \
          -p 53:53/udp \
          -p 53:53/tcp \
          skynetservices/skydns
        ExecStop=/usr/bin/docker stop skydns
    - name: skydns-register-primary-nameserver.service
      command: start
      content: |
        [Unit]
        Description=Registers this server as NS in SkyDNS config
        Requires=etcd.service
        After=etcd.service
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/etcdctl set /skydns/local/gainmaster/dns/ns '{"host":"$private_ipv4"}'
    - name: node-skydns-registrator.service
      command: start
      content: |
        [Unit]
        Description=Registers node in SkyDNS
        Requires=etcd.service
        After=etcd.service
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/etcdctl set /skydns/local/gainmaster/nodes/coreos '{"host":"$private_ipv4"}'
    - name: docker-etcd-registrator.service
      command: start
      content: |
        [Unit]
        Description=Docker etcd registrator service
        Requires=etcd.service
        After=etcd.service
        Requires=docker.service
        After=docker.service
        [Service]
        TimeoutStartSec=0
        KillMode=none
        ExecStartPre=-/usr/bin/docker kill registrator
        ExecStartPre=-/usr/bin/docker rm registrator
        ExecStartPre=/usr/bin/docker pull gliderlabs/registrator
        ExecStart=/usr/bin/docker run --rm --name registrator \
          -v /var/run/docker.sock:/tmp/docker.sock \
          -h %H \
          gliderlabs/registrator etcd://$private_ipv4:4001/registrator -resync 5
    - name: vulcand.service
      command: start
      content: |
        [Unit]
        Description=Vulcand HTTP service
        Requires=etcd.service
        After=etcd.service
        Requires=docker.service
        After=docker.service
        Requires=vulcand-skydns-registrator.service
        Before=vulcand-skydns-registrator.service
        [Service]
        TimeoutStartSec=0
        KillMode=none
        ExecStartPre=-/usr/bin/docker kill vulcand
        ExecStartPre=-/usr/bin/docker rm vulcand
        ExecStartPre=/usr/bin/docker pull mailgun/vulcand:v0.8.0-beta.2
        ExecStart=/usr/bin/docker run --rm --name vulcand \
          -p 80:80 \
          mailgun/vulcand:v0.8.0-beta.2 \
          /go/bin/vulcand \
          -port=80 \
          --etcd=http://$private_ipv4:4001
    - name: vulcand-skydns-registrator.service
      command: start
      content: |
          [Unit]
          Description=Register Vulcand HTTP service in SkyDNS
          Requires=etcd.service
          After=etcd.service
          BindsTo=vulcand.service
          After=vulcand.service
          [Service]
          Type=oneshot
          ExecStart=/usr/bin/etcdctl set /skydns/local/gainmaster/services/http/vulcand '{"Host": "$public_ipv4"}'
    - name: 00-et.network
      runtime: true
      content: |
        [Match]
        Name=eth*
        [Network]
        DNS=$public_ipv4
        DNS=8.8.8.8
write_files:
  - path: /etc/metadata
    permissions: 0644
    content: |
      PUBLIC_IPV4=$public_ipv4
      PRIVATE_IPV4=$private_ipv4
      SHARED_DATA=/mnt/shared
      GAINMASTER_DOMAIN=gainmaster.local
      SKYDNS_DOMAIN_PATH=local/gainmaster