#cloud-config

coreos:
    etcd:
        addr     : $private_ipv4:4001
        peer-addr: $private_ipv4:7001
        discovery: https://discovery.etcd.io/<token>

    fleet:
        public-ip: $private_ipv4
        metadata : 'location=developer,public=true,name=coreos1,role=gainmaster'

    units:
      - name   : etcd.service
        command: start

      - name   : fleet.service
        command: start

      - name   : docker.socket
        command: start
        drop-ins: 
          - name: 30-ListenStream.conf
            content: |
                [Socket]
                ListenStream=$private_ipv4:2375

      - name: development-machine.service
        enable: true
        content: |
            [Unit]
            Description=machine
            After=docker.service
            Requires=docker.service
            [Service]
            TimeoutStartSec=0
            Restart=always
            RestartSec=10s
            ExecStart=/bin/bash -c 'sudo systemd-nspawn \
                --machine gainmaster \
                --quiet \
                --keep-unit \
                --boot \
                --link-journal=guest \
                --directory /machine \
                --bind /volumes \
                --bind /usr/bin/docker \
                --bind /usr/bin/etcdctl \
                --bind /usr/bin/fleetctl \
                --bind /projects \
                systemctl start sshd'
            ExecStop=/bin/bash -c 'sudo machinectl terminate machine'
            [Install]
            WantedBy=multi-user.target

      - name: 00-et.network
        runtime: true
        content: |
            [Match]
            Name=eth*
            [Network]
            DNS=$public_ipv4
            DNS=8.8.8.8

write_files:
  - path: /etc/coreos_metadata
    permissions: 644
    content: |
        PUBLIC_IPV4=$public_ipv4
        PRIVATE_IPV4=$private_ipv4
        SHARED_DATA=/mnt/shared

  - path: /etc/gainmaster_metadata
    permissions: 644
    content: |
        GAINMASTER_DOMAIN=gainmaster.local
        SKYDNS_DOMAIN_PATH=local/gainmaster